---@type LazySpec
return {
    -- {
    --     "vhyrro/luarocks.nvim",
    --     priority = 1000,
    --     config = true,
    --     opts = {
    --         -- rocks = { "lua-curl", "nvim-nio", "mimetypes", "xml2lua" }
    --     }
    -- },
    --
    -- {
    --     "rest-nvim/rest.nvim",
    --
    --     dependencies = {
    --         'nvim-treesitter/nvim-treesitter',
    --         'luarocks.nvim',
    --     },
    --
    --     ft = "http",
    --
    --     ---@type RestConfig
    --     opts = {
    --     },
    --
    --     config = function(_, opts)
    --         require("rest-nvim").setup(opts)
    --     end,
    -- },


    -- -- {
    -- --     'vhyrro/luarocks.nvim',
    -- --     -- dependencies = {
    -- --     --     'rcarriga/nvim-notify',
    -- --     -- },
    -- --
    -- --     opts = {
    -- --         -- rocks = { 'lua-curl', 'nvim-nio', 'mimetypes', 'xml2lua' },
    -- --     },
    -- --
    -- --     config = function(_, opts)
    -- --         require("luarocks").setup(opts)
    -- --     end,
    -- -- },
    -- {
    --     "rest-nvim/rest.nvim", -- https://github.com/rest-nvim/rest.nvim
    --
    --     dependencies = {
    --         'nvim-treesitter/nvim-treesitter',
    --         {
    --             "vhyrro/luarocks.nvim",
    --             priority = 1000, -- Very high priority is required, luarocks.nvim should run as the first plugin in your config.
    --             config = true,
    --         }
    --     },
    --
    --     ft = { 'http' },
    --
    --     keys = {
    --         { '<leader>rq', '<CMD>Rest run<CR>', buffer = true, desc = '[r]est-nvim re[q]uest' },
    --
    --         -- NOTE: there is no binding to preview cURL cmd in rest.nvim v2
    --     },
    --
    --     opts = {
    --         -- TODO: use opts for rest.nvim v2
    --     },
    --
    --     config = function(_, opts)
    --         local rest_nvim = require('rest-nvim')
    --         rest_nvim.setup(opts)
    --     end,
    -- }
}
