#:schema ../symlonk-schema.json

[config]
extends = "../symlonk-config.toml"
source_dir = "."

[symlinks]
".config/opencode/config" = "config/tui.toml"
".config/opencode/providers" = "config/providers"
# "opencode.jsonc" = "config/opencode.jsonc"
