#!/bin/bash
#
# Initialize local git config and create symlinks in $HOME.
#
# Adapted from https://github.com/holman/dotfiles/blob/master/script/bootstrap

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
GITCONFIG_FILE=git/gitconfig.local
GITCONFIG_TEMPLATE=$GITCONFIG_FILE.template

set -e

echo ''

info () {
  printf "\r  [\033[00;34minfo\033[0m] %s\n" "$1"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] %b\n" "$1"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
  echo ''
  exit 1
}

setup_gitconfig () {
  if ! [ -f "$GITCONFIG_FILE" ]
  then
    info 'setup gitconfig'
    if [ ! -f $GITCONFIG_TEMPLATE ]
    then
      fail "could not find local gitconfig template '$GITCONFIG_TEMPLATE'"
    fi

    git_credential='cache'

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" "$GITCONFIG_TEMPLATE" > "$GITCONFIG_FILE"
    # echo "$GITCONFIG_FILE:.gitconfig" > git/symlinks.conf

    success 'gitconfig'
  fi
}

setup_symlinks () {
  # install symlonk
  if ! which symlonk >/dev/null; then 
    fail "could not find symlonk executable: install https://github.com/louis-brunet/symlonk"
  fi

  # run symlonk
  symlonk create links "$DOTFILES_ROOT"/*/symlonk.toml --prune --verify
}

setup_gitconfig
setup_symlinks

echo ''
echo '  All installed!'

