#!/bin/bash
#
# Run all dotfiles installers.
#
# Yoinked from https://github.com/holman/dotfiles/blob/master/script/install

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -maxdepth 2 -name install.sh -not -path './scripts/*' -not -path '*.git*' | while read installer ; do sh -c "echo '${installer}' && ${installer}" ; done

