services:
  webui:
    image: 'ghcr.io/open-webui/open-webui:main'
    restart: 'no'
    # restart: 'unless-stopped'
    volumes:
      - 'open-webui:/app/backend/data'
    ports:
      - '3000:8080'
    # environment:

volumes:
  open-webui:
