#:schema ../symlonk-schema.json

[config]
extends = "../../symlonk-config.toml"
source_dir = "."

[symlinks]
".config/opencode/opencode.jsonc" = "config/opencode.jsonc"
".config/opencode/tui.json" = "config/tui.json"
".config/opencode/themes" = "config/themes"
".config/opencode/agents" = "config/agents"
".config/opencode/commands" = "config/commands"
".config/opencode/skills" = "config/skills"
".config/opencode/tools" = "config/tools"
