#:schema ../symlonk-schema.json

[config]
extends = "../../symlonk-config.toml"
source_dir = "."

[symlinks]
".config/opencode/config.json" = "config/config.json"
".config/opencode/tui.json" = "config/tui.json"
# # ".config/opencode/themes" = "config/themes"
".config/opencode/agent" = "config/agent"
".config/opencode/command" = "config/command"
".config/opencode/skills" = "config/skills"
".config/opencode/tool" = "config/tool"
